### ISSUE TITLE
object has no attribute 'queryset'

### ISSUE THREAD

**Issue by actongorton** [OskarPersson/django-nested-inline#31]
Vanilla install with Django 1.8 using examples in docs gets 'LevelOneInline' object has no attribute 'queryset'.

**Comment by chawchaw** [comment]
In admin.py with Django 1.8(1.7 is ok),
```
nested_inline.queryset(request)
inline.queryset(request)
```
raise error. There are 6 calls.

I changed all to 
```
nested_inline.get_queryset(request)
inline.get_queryset(request)
```
and it works.

**Comment by GabKlein** [comment]
@chawchaw Could you provide us with more details on how you solved this issue?

**Comment by chawchaw** [comment]
@GabKlein 
There is a pull request about this issue.
Check it following.
https://github.com/s-block/django-nested-inline/pull/32/files

**Comment by nwaxiomatic** [comment]
did this get pulled?

**Comment by YaderV** [comment]
The support for django 1.8 was added in another pull request. The latest version works well for me, but it's not available via pip yet.
